### ISSUE TITLE
Environment for data downloading

### ISSUE THREAD

**Issue by JegZheng** [Computer-Vision-in-the-Wild/DataDownload#1]
Hi, 

Thanks for the great work. When downloading the image classification datasets, I encountered the following error:

Traceback (most recent call last):
  File "download_datasets.py", line 18, in <module>
    hub = DatasetHub(pathlib.Path('./resources/vision_datasets.json').read_text())
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/vision_datasets/resources/dataset_hub.py", line 25, in __init__
    self.dataset_registry = DatasetRegistry(dataset_json_str)
  File "/anaconda/envs/azureml_py38/lib/python3.8/site-packages/vision_datasets/common/dataset_registry.py", line 12, in __init__
    self.datasets = [DatasetInfoFactory.create(d) for d in json.loads(datasets_json)]
  File "/anaconda/envs/azureml_py38/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/anaconda/envs/azureml_py38/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/anaconda/envs/azureml_py38/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 559 column 1 (char 17335)

I think this error is raised by the incompatibility of the package version. I am using Pytorch==1.8.1, and vision_datasets==0.2.12. Could you please list the correct package version in the README? Thanks!

**Comment by haotian-liu** [comment]
The only package requirement for downloading the classification datasets is `vision-datasets>=0.2.0`.  The error above now been fixed by updating the JSON file in the repo, and thanks for pointing this out!

Please use the latest code base to download the datasets.  Thank you!

**Comment by JegZheng** [comment]
> The only package requirement for downloading the classification datasets is `vision-datasets>=0.2.0`. The error above now been fixed by updating the JSON file in the repo, and thanks for pointing this out!
> 
> Please use the latest code base to download the datasets. Thank you!

Thanks! This addresses my issue well. BTW the json file in the Elevater_Toolkit_IC repo might need also this update.

**Comment by haotian-liu** [comment]
Thanks for the kind reminder!  It has now been updated as well.
