### ISSUE TITLE
Classification dataset not found: `ping-attack-on-titan-plus`

### ISSUE THREAD

**Issue by andsteing** [Computer-Vision-in-the-Wild/DataDownload#5]
When running the command

```bash
python download_datasets.py --ds all
```

I get the following error:

```
Downloading dataset: caltech-101...
Dataset download finishes: caltech-101.
Downloading dataset: cifar-10...
Dataset download finishes: cifar-10.
Downloading dataset: cifar-100...
Dataset download finishes: cifar-100.
Downloading dataset: country211...
Dataset download finishes: country211.
Downloading dataset: dtd...
Dataset download finishes: dtd.
Downloading dataset: eurosat_clip...
Dataset download finishes: eurosat_clip.
Downloading dataset: fer-2013...
Dataset download finishes: fer-2013.
Downloading dataset: fgvc-aircraft-2013b-variants102...
Dataset download finishes: fgvc-aircraft-2013b-variants102.
Downloading dataset: food-101...
Dataset download finishes: food-101.
Downloading dataset: gtsrb...
Dataset download finishes: gtsrb.
Downloading dataset: hateful-memes...
Dataset download finishes: hateful-memes.
Downloading dataset: kitti-distance...
Dataset download finishes: kitti-distance.
Downloading dataset: mnist...
Dataset download finishes: mnist.
Downloading dataset: oxford-flower-102...
Dataset download finishes: oxford-flower-102.
Downloading dataset: oxford-iiit-pets...
Dataset download finishes: oxford-iiit-pets.
Downloading dataset: patch-camelyon...
Dataset download finishes: patch-camelyon.
Downloading dataset: ping-attack-on-titan-plus...
Traceback (most recent call last):
  File "download_datasets.py", line 30, in <module>
    download(ds)
  File "download_datasets.py", line 23, in download
    downloader.download(ds, target_dir=args.output_dir, purposes=[Usages.TRAIN_PURPOSE, Usages.VAL_PURPOSE, Usages.TEST_PURPOSE])
  File "/usr/local/lib/python3.7/dist-packages/vision_datasets/common/dataset_downloader.py", line 59, in download
    raise RuntimeError(f'No dataset matched for the specified condition: {name} ({version})')
RuntimeError: No dataset matched for the specified condition: ping-attack-on-titan-plus (None)
```

What is the purpose of the datasetes `ping-attack-on-titan-plus` and `ping-whiskey-plus`?

I can't find them in the appendix C.1 of the ELEVATER paper https://arxiv.org/abs/2204.08790:
![image](https://user-images.githubusercontent.com/16050001/188420810-c90fd999-3cf9-4f81-87cc-5d7065e94e0c.png)

**Comment by ChunyuanLI** [comment]
Sorry for the confusion. The two datasets are removed from the list. They should not be considered at this moment. Thanks.
